language: cpp

dist: trusty
sudo: false

compiler:
  - clang
  - gcc

env:
  - OMP_NUM_THREADS=2

script:
  - cmake -E make_directory build
  - cmake -E chdir build cmake ..
  - cmake --build build
  - cmake -E chdir build ctest

notifications:
  - email: false
